In [1]:
import pandas as pd   
import numpy as np 

In [2]:
df = pd.read_csv('heart_2020_cleaned.csv')
df

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  16.60     Yes              No     No             3.0   
1                No  20.34      No              No    Yes             0.0   
2                No  26.58     Yes              No     No            20.0   
3                No  24.21      No              No     No             0.0   
4                No  23.71      No              No     No            28.0   
...             ...    ...     ...             ...    ...             ...   
319790          Yes  27.41     Yes              No     No             7.0   
319791           No  29.84     Yes              No     No             0.0   
319792           No  24.24      No              No     No             0.0   
319793           No  32.81      No              No     No             0.0   
319794           No  46.56      No              No     No             0.0   

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes   
1                0.0          No  Female  80 or older     White       No   
2               30.0          No    Male        65-69     White      Yes   
3                0.0          No  Female        75-79     White       No   
4                0.0         Yes  Female        40-44     White       No   
...              ...         ...     ...          ...       ...      ...   
319790           0.0         Yes    Male        60-64  Hispanic      Yes   
319791           0.0          No    Male        35-39  Hispanic       No   
319792           0.0          No  Female        45-49  Hispanic       No   
319793           0.0          No  Female        25-29  Hispanic       No   
319794           0.0          No  Female  80 or older  Hispanic       No   

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0                   Yes  Very good        5.0    Yes            No        Yes  
1                   Yes  Very good        7.0     No            No         No  
2                   Yes       Fair        8.0    Yes            No         No  
3                    No       Good        6.0     No            No        Yes  
4                   Yes  Very good        8.0     No            No         No  
...                 ...        ...        ...    ...           ...        ...  
319790               No       Fair        6.0    Yes            No         No  
319791              Yes  Very good        5.0    Yes            No         No  
319792              Yes       Good        6.0     No            No         No  
319793               No       Good       12.0     No            No         No  
319794              Yes       Good        8.0     No            No         No  

[319795 rows x 18 columns]

In [3]:
subdf = df.iloc[:30,:].copy()
subdf.shape

(30, 18)

In [4]:
subdf.dtypes

HeartDisease         object
BMI                 float64
Smoking              object
AlcoholDrinking      object
Stroke               object
PhysicalHealth      float64
MentalHealth        float64
DiffWalking          object
Sex                  object
AgeCategory          object
Race                 object
Diabetic             object
PhysicalActivity     object
GenHealth            object
SleepTime           float64
Asthma               object
KidneyDisease        object
SkinCancer           object
dtype: object

In [5]:
subdf.nunique()

HeartDisease         2
BMI                 29
Smoking              2
AlcoholDrinking      1
Stroke               2
PhysicalHealth      12
MentalHealth         6
DiffWalking          2
Sex                  2
AgeCategory          9
Race                 2
Diabetic             3
PhysicalActivity     2
GenHealth            5
SleepTime            9
Asthma               2
KidneyDisease        2
SkinCancer           2
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in df.columns:
    if df[i].dtype == 'object':
        df[i] = le.fit_transform(df[i])


In [7]:
df
# 0 = female 
# 1 = white
#

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0                  0  16.60        1                0       0             3.0   
1                  0  20.34        0                0       1             0.0   
2                  0  26.58        1                0       0            20.0   
3                  0  24.21        0                0       0             0.0   
4                  0  23.71        0                0       0            28.0   
...              ...    ...      ...              ...     ...             ...   
319790             1  27.41        1                0       0             7.0   
319791             0  29.84        1                0       0             0.0   
319792             0  24.24        0                0       0             0.0   
319793             0  32.81        0                0       0             0.0   
319794             0  46.56        0                0       0             0.0   

        MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0               30.0            0    0            7     5         2   
1                0.0            0    0           12     5         0   
2               30.0            0    1            9     5         2   
3                0.0            0    0           11     5         0   
4                0.0            1    0            4     5         0   
...              ...          ...  ...          ...   ...       ...   
319790           0.0            1    1            8     3         2   
319791           0.0            0    1            3     3         0   
319792           0.0            0    0            5     3         0   
319793           0.0            0    0            1     3         0   
319794           0.0            0    0           12     3         0   

        PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  \
0                      1          4        5.0       1              0   
1                      1          4        7.0       0              0   
2                      1          1        8.0       1              0   
3                      0          2        6.0       0              0   
4                      1          4        8.0       0              0   
...                  ...        ...        ...     ...            ...   
319790                 0          1        6.0       1              0   
319791                 1          4        5.0       1              0   
319792                 1          2        6.0       0              0   
319793                 0          2       12.0       0              0   
319794                 1          2        8.0       0              0   

        SkinCancer  
0                1  
1                0  
2                0  
3                1  
4                0  
...            ...  
319790           0  
319791           0  
319792           0  
319793           0  
319794           0  

[319795 rows x 18 columns]

In [8]:
df

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0                  0  16.60        1                0       0             3.0   
1                  0  20.34        0                0       1             0.0   
2                  0  26.58        1                0       0            20.0   
3                  0  24.21        0                0       0             0.0   
4                  0  23.71        0                0       0            28.0   
...              ...    ...      ...              ...     ...             ...   
319790             1  27.41        1                0       0             7.0   
319791             0  29.84        1                0       0             0.0   
319792             0  24.24        0                0       0             0.0   
319793             0  32.81        0                0       0             0.0   
319794             0  46.56        0                0       0             0.0   

        MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0               30.0            0    0            7     5         2   
1                0.0            0    0           12     5         0   
2               30.0            0    1            9     5         2   
3                0.0            0    0           11     5         0   
4                0.0            1    0            4     5         0   
...              ...          ...  ...          ...   ...       ...   
319790           0.0            1    1            8     3         2   
319791           0.0            0    1            3     3         0   
319792           0.0            0    0            5     3         0   
319793           0.0            0    0            1     3         0   
319794           0.0            0    0           12     3         0   

        PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  \
0                      1          4        5.0       1              0   
1                      1          4        7.0       0              0   
2                      1          1        8.0       1              0   
3                      0          2        6.0       0              0   
4                      1          4        8.0       0              0   
...                  ...        ...        ...     ...            ...   
319790                 0          1        6.0       1              0   
319791                 1          4        5.0       1              0   
319792                 1          2        6.0       0              0   
319793                 0          2       12.0       0              0   
319794                 1          2        8.0       0              0   

        SkinCancer  
0                1  
1                0  
2                0  
3                1  
4                0  
...            ...  
319790           0  
319791           0  
319792           0  
319793           0  
319794           0  

[319795 rows x 18 columns]

In [9]:
df.nunique()

HeartDisease           2
BMI                 3604
Smoking                2
AlcoholDrinking        2
Stroke                 2
PhysicalHealth        31
MentalHealth          31
DiffWalking            2
Sex                    2
AgeCategory           13
Race                   6
Diabetic               4
PhysicalActivity       2
GenHealth              5
SleepTime             24
Asthma                 2
KidneyDisease          2
SkinCancer             2
dtype: int64

In [10]:
for i in df.columns: 
    print(f" {df[i].unique()}")

 [0 1]
 [16.6  20.34 26.58 ... 62.42 51.46 46.56]
 [1 0]
 [0 1]
 [0 1]
 [ 3.  0. 20. 28.  6. 15.  5. 30.  7.  1.  2. 21.  4. 10. 14. 18.  8. 25.
 16. 29. 27. 17. 24. 12. 23. 26. 22. 19.  9. 13. 11.]
 [30.  0.  2.  5. 15.  8.  4.  3. 10. 14. 20.  1.  7. 24.  9. 28. 16. 12.
  6. 25. 17. 18. 21. 29. 22. 13. 23. 27. 26. 11. 19.]
 [0 1]
 [0 1]
 [ 7 12  9 11  4 10  8  6  5  0  3  2  1]
 [5 2 1 0 4 3]
 [2 0 1 3]
 [1 0]
 [4 1 2 3 0]
 [ 5.  7.  8.  6. 12.  4.  9. 10. 15.  3.  2.  1. 16. 18. 14. 20. 11. 13.
 17. 24. 19. 21. 22. 23.]
 [1 0]
 [0 1]
 [1 0]


In [11]:
df 

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0                  0  16.60        1                0       0             3.0   
1                  0  20.34        0                0       1             0.0   
2                  0  26.58        1                0       0            20.0   
3                  0  24.21        0                0       0             0.0   
4                  0  23.71        0                0       0            28.0   
...              ...    ...      ...              ...     ...             ...   
319790             1  27.41        1                0       0             7.0   
319791             0  29.84        1                0       0             0.0   
319792             0  24.24        0                0       0             0.0   
319793             0  32.81        0                0       0             0.0   
319794             0  46.56        0                0       0             0.0   

        MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0               30.0            0    0            7     5         2   
1                0.0            0    0           12     5         0   
2               30.0            0    1            9     5         2   
3                0.0            0    0           11     5         0   
4                0.0            1    0            4     5         0   
...              ...          ...  ...          ...   ...       ...   
319790           0.0            1    1            8     3         2   
319791           0.0            0    1            3     3         0   
319792           0.0            0    0            5     3         0   
319793           0.0            0    0            1     3         0   
319794           0.0            0    0           12     3         0   

        PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  \
0                      1          4        5.0       1              0   
1                      1          4        7.0       0              0   
2                      1          1        8.0       1              0   
3                      0          2        6.0       0              0   
4                      1          4        8.0       0              0   
...                  ...        ...        ...     ...            ...   
319790                 0          1        6.0       1              0   
319791                 1          4        5.0       1              0   
319792                 1          2        6.0       0              0   
319793                 0          2       12.0       0              0   
319794                 1          2        8.0       0              0   

        SkinCancer  
0                1  
1                0  
2                0  
3                1  
4                0  
...            ...  
319790           0  
319791           0  
319792           0  
319793           0  
319794           0  

[319795 rows x 18 columns]

In [12]:
df.corr()


HeartDisease       BMI   Smoking  AlcoholDrinking    Stroke  \
HeartDisease          1.000000  0.051803  0.107764        -0.032080  0.196835   
BMI                   0.051803  1.000000  0.023118        -0.038816  0.019733   
Smoking               0.107764  0.023118  1.000000         0.111768  0.061226   
AlcoholDrinking      -0.032080 -0.038816  0.111768         1.000000 -0.019858   
Stroke                0.196835  0.019733  0.061226        -0.019858  1.000000   
PhysicalHealth        0.170721  0.109788  0.115352        -0.017254  0.137014   
MentalHealth          0.028591  0.064131  0.085157         0.051282  0.046467   
DiffWalking           0.201258  0.181678  0.120074        -0.035328  0.174143   
Sex                   0.070040  0.026940  0.085052         0.004200 -0.003091   
AgeCategory           0.233432 -0.004744  0.128331        -0.059528  0.137822   
Race                  0.034854 -0.037424  0.065499         0.036702 -0.003956   
Diabetic              0.168553  0.202472  0.053847        -0.057372  0.101518   
PhysicalActivity     -0.100030 -0.150616 -0.097174         0.017487 -0.079455   
GenHealth            -0.011062  0.035932  0.020625         0.001629 -0.009335   
SleepTime             0.008327 -0.051822 -0.030336        -0.005065  0.011900   
Asthma                0.041444  0.092345  0.024149        -0.002202  0.038866   
KidneyDisease         0.145197  0.050768  0.034920        -0.028280  0.091167   
SkinCancer            0.093317 -0.033644  0.033977        -0.005702  0.048116   

                  PhysicalHealth  MentalHealth  DiffWalking       Sex  \
HeartDisease            0.170721      0.028591     0.201258  0.070040   
BMI                     0.109788      0.064131     0.181678  0.026940   
Smoking                 0.115352      0.085157     0.120074  0.085052   
AlcoholDrinking        -0.017254      0.051282    -0.035328  0.004200   
Stroke                  0.137014      0.046467     0.174143 -0.003091   
PhysicalHealth          1.000000      0.287987     0.428373 -0.040904   
MentalHealth            0.287987      1.000000     0.152235 -0.100058   
DiffWalking             0.428373      0.152235     1.000000 -0.068860   
Sex                    -0.040904     -0.100058    -0.068860  1.000000   
AgeCategory             0.110763     -0.155506     0.243263 -0.067478   
Race                   -0.000847     -0.014491    -0.015831  0.018855   
Diabetic                0.151361      0.032945     0.205502 -0.013456   
PhysicalActivity       -0.232283     -0.095808    -0.278524  0.048247   
GenHealth              -0.035703     -0.004412    -0.043552 -0.010283   
SleepTime              -0.061387     -0.119717    -0.022216 -0.015704   
Asthma                  0.117907      0.114008     0.103222 -0.069191   
KidneyDisease           0.142197      0.037281     0.153064 -0.009084   
SkinCancer              0.041700     -0.033412     0.064840  0.013434   

                  AgeCategory      Race  Diabetic  PhysicalActivity  \
HeartDisease         0.233432  0.034854  0.168553         -0.100030   
BMI                 -0.004744 -0.037424  0.202472         -0.150616   
Smoking              0.128331  0.065499  0.053847         -0.097174   
AlcoholDrinking     -0.059528  0.036702 -0.057372          0.017487   
Stroke               0.137822 -0.003956  0.101518         -0.079455   
PhysicalHealth       0.110763 -0.000847  0.151361         -0.232283   
MentalHealth        -0.155506 -0.014491  0.032945         -0.095808   
DiffWalking          0.243263 -0.015831  0.205502         -0.278524   
Sex                 -0.067478  0.018855 -0.013456          0.048247   
AgeCategory          1.000000  0.163090  0.193745         -0.121687   
Race                 0.163090  1.000000 -0.052216          0.056767   
Diabetic             0.193745 -0.052216  1.000000         -0.133824   
PhysicalActivity    -0.121687  0.056767 -0.133824          1.000000   
GenHealth            0.044427  0.050344 -0.010854          0.024418   
SleepTime            0.10

In [13]:
for i in range(0,100,10):    
    print(df[df['BMI']>i]['BMI'].value_counts().sum(), i)


319795 0
319795 10
305096 20
102548 30
16350 40
2511 50
492 60
129 70
34 80
8 90


In [14]:
bmi_60_plus = df[df['BMI']>60].index
df.drop(bmi_60_plus, inplace=True)


In [15]:
for i in range(0,100,10):    
    print(df[df['BMI']>i]['BMI'].value_counts().sum(), i)


319303 0
319303 10
304604 20
102056 30
15858 40
2019 50
0 60
0 70
0 80
0 90


In [25]:
df.loc[:,'HeartDisease'].to_clipboard(index = False, header = False)

In [18]:
HeartDisease	BMI	Smoking	AlcoholDrinking	Stroke	PhysicalHealth	MentalHealth	DiffWalking	Sex	AgeCategory	Race	Diabetic	PhysicalActivity	GenHealth	SleepTime	Asthma	KidneyDisease	SkinCancer

SyntaxError: invalid syntax (660391064.py, line 1)